apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ab-activityservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ab-activityservice-deployment
  minReplicas: 2
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5  # Target: 50% of the CPU limit (500m)

