# ---------- DEPLOYMENT ----------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway

  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
        - name: wait-for-config-server
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for Config Server..."
              until curl -sf http://config-server:8888/actuator/health | grep '"status":"UP"' > /dev/null; do
                echo "Config Server not ready..."
                sleep 3
              done
              echo "Config Server is UP!"

      containers:
        - name: gateway
          image: ab-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4441

          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 4441
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 20

          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 4441
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2

---
# ---------- SERVICE ----------
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 4441
      targetPort: 4441
  type: ClusterIP

